server:
  port: ${PORT:8080}

spring:
  application:
    name: news-crawler-backend
  
  # 프로파일별 설정
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  
  # 데이터베이스 설정
  datasource:
    url: ${DATABASE_URL:jdbc:h2:file:./data/testdb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
  
  # H2 콘솔 (로컬 개발용)
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: /h2-console

# 로깅 설정
logging:
  level:
    com.newscrawler: ${LOG_LEVEL:DEBUG}
    org.springframework.web: ${WEB_LOG_LEVEL:INFO}
    org.hibernate.SQL: ${SQL_LOG_LEVEL:DEBUG}

# CORS 설정
cors:
  allowed-origins: ${CORS_ORIGINS:https://crawling-jejy.onrender.com,http://localhost:3000,http://localhost:5173}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"

# 크롤링 설정
crawler:
  enabled: ${CRAWLER_ENABLED:true}
  max-articles-per-site: ${MAX_ARTICLES_PER_SITE:10}
  connection-timeout: ${CONNECTION_TIMEOUT:30000}
  user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

# 데이터 정리 설정
cleanup:
  keep-days: ${CLEANUP_KEEP_DAYS:30}

# YouTube API 설정 (보안)
youtube:
  api-key: ${YOUTUBE_API_KEY:your-youtube-api-key}
  client-id: ${YOUTUBE_CLIENT_ID:your-client-id}
  client-secret: ${YOUTUBE_CLIENT_SECRET:your-client-secret}
  refresh-token: ${YOUTUBE_REFRESH_TOKEN:your-refresh-token}
  channel-id: ${YOUTUBE_CHANNEL_ID:your-channel-id}

# 무료 TTS 설정
tts:
  provider: ${TTS_PROVIDER:edge-tts}  # edge-tts, espeak, piper
  edge:
    voice: ${EDGE_TTS_VOICE:ko-KR-SunHiNeural}  # 한국어 여성 목소리
    rate: ${EDGE_TTS_RATE:+0%}  # 속도 조절
    pitch: ${EDGE_TTS_PITCH:+0Hz}  # 피치 조절
  espeak:
    voice: ${ESPEAK_VOICE:ko}
    speed: ${ESPEAK_SPEED:175}
    pitch: ${ESPEAK_PITCH:50}

# 영상 생성 설정
video:
  generation:
    enabled: ${VIDEO_GENERATION_ENABLED:false}
    output-directory: ${VIDEO_OUTPUT_DIR:./videos}
    max-duration-seconds: ${VIDEO_MAX_DURATION:30}
    resolution: ${VIDEO_RESOLUTION:1080x1920}  # 세로형 (숏폼)
    frame-rate: ${VIDEO_FRAME_RATE:30}

---
# Production 프로파일 (Render)
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: ${SPRING_DATASOURCE_URL:${DATABASE_URL}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USERNAME}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        # PostgreSQL dialect은 자동 감지되므로 명시하지 않음
  h2:
    console:
      enabled: false

logging:
  level:
    com.newscrawler: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN

cors:
  allowed-origins: ${FRONTEND_URL:https://crawling-jejy.onrender.com}

---
# Development 프로파일
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/newscrawler
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
